<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Flux.Protocol/Flux.Protocol.csproj" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
    <Compile Include="../Flux.Windows/DiscoveryCatalog.cs" Link="DiscoveryCatalog.cs" />
    <Compile Include="../Flux.Windows/PeerSession.cs" Link="PeerSession.cs" />
  </ItemGroup>
</Project>
